Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Style/BlockDelimiters:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'db/migrate/*'
    - 'db/**/*'
    - 'test/**/*'
    - 'config/**/*'
  TargetRubyVersion: 3.1.2
  SuggestExtensions: true